### Authenticate with user and pass
POST http://localhost:7072/api/Authenticate HTTP/1.1
Content-Type: application/json

{
	"username":"",
	"password":"smu2"
}

### Authenticate with code

POST http://localhost:7071/api/Authenticate HTTP/1.1
Content-Type: application/json

{
	"code": "d6148a6b2f4f456a898de6380a1fa814"
}

