### Authenticate with user and pass
POST http://localhost:7072/api/Authenticate HTTP/1.1
Content-Type: application/json

{
	"username":"kromby",
	"password":null
}

### Authenticate with code

POST http://localhost:7071/api/Authenticate HTTP/1.1
Content-Type: application/json

{
	"code": "d6148a6b2f4f456a898de6380a1fa814"
}

### Create magic code
POST http://localhost:7072/api/authenticate/magic
X-Custom-Authorization: token eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNjMwIiwiZXhwIjoxNjU2ODc4Njg1LCJpc3MiOiJIcmVzcyIsImF1ZCI6ImhyZXNzcmVhY3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.KYyEzbRBnBfTVjzHo8pTGaVrY9FjfjTI9iepNVTlRlI