### Authenticate with code

POST https://ezhressapi.azurewebsites.net/api/authenticate?code=JRXXeaXTE5Y9WD2kVAYLu6gXknrmLlluqfTJZfo3pZfo4kkBUzf3Yw==
Content-Type: application/json

{
	"code": "d6148a6b2f4f456a898de6380a1fa814"
}