### Authenticate with code

POST https://ezhressapi.azurewebsites.net/api/authenticate?code=JRXXeaXTE5Y9WD2kVAYLu6gXknrmLlluqfTJZfo3pZfo4kkBUzf3Yw==
Content-Type: application/json

{
	"code": "d229386d772e47e6a755b337e6de71ac"
}