### Get all dinner parties
GET http://localhost:7072/api/dinnerParties

### Get a single dinner party
GET http://localhost:7072/api/dinnerParties/5304

### Get all courses for a single dinner party
GET http://localhost:7072/api/dinnerParties/5304/courses

### Get all courses by typeID
GET http://localhost:7072/api/dinnerparties/courses/191

### Post vote on course
POST http://localhost:7072/api/dinnerparties/courses/999
Content-Type: application/json
X-Custom-Authorization: token eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNjMwIiwiZXhwIjoxNjY3NTIyMjQzLCJpc3MiOiJIcmVzcyIsImF1ZCI6ImhyZXNzcmVhY3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.9045b9OAnRRSPMOb9xAdat_7zJIkbB1vYrbnbnefH-k

{
    "courseID": 9979
}

### Get redwine teams
GET http://localhost:7072/api/dinnerparties/5383/teams