### Post nominations
POST http://localhost:7072/api/hardhead/awards/nominations
Content-Type: application/json
X-Custom-Authorization: token eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNjMwIiwiZXhwIjoxNjU2MjA2NDA1LCJpc3MiOiJIcmVzcyIsImF1ZCI6ImhyZXNzcmVhY3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.23SIOu78T1_aGHUVVjDHxm_sNzVojA_b_bmXxiovZ-Y

{
    "description": "Kromby 101",
    "typeID": 207,
    "nomineeID": 2640,
    "createdBy": 2630
}

### Get nominations
GET http://localhost:7072/api/hardhead/awards/nominations?type=207
Content-Type: application/json
X-Custom-Authorization: token eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNjMwIiwiZXhwIjoxNjU2MjA2NDA1LCJpc3MiOiJIcmVzcyIsImF1ZCI6ImhyZXNzcmVhY3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.23SIOu78T1_aGHUVVjDHxm_sNzVojA_b_bmXxiovZ-Y