### Get user statistic by periodType
GET {{host}}/api/hardhead/statistics/users?periodType=2

### Get user statistic by periodType and attendanceType
GET {{host}}/api/hardhead/statistics/users/2630?attendanceType=53&periodType=1

### Get attendance statistic by periodType
GET {{host}}/api/hardhead/statistics/attendances?periodType=2

### Get history of challenges to and from a specific user
GET {{host}}/api/hardhead/statistics/users/2630/challenges

### Get streaks for a specific user
GET {{host}}/api/hardhead/statistics/users/2652/streaks