### Post nominations
POST https://vefur.hress.org/api/hardhead/awards/nominations
 Content-Type: application/json
 X-Custom-Authorization: token eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNjMwIiwiZXhwIjoxNjU1NzY5ODcwLCJpc3MiOiJIcmVzcyIsImF1ZCI6ImhyZXNzcmVhY3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.vxjhzIUWh3oS-Qzeoknf5MUG0eIdgT5jupggpfGo8Qg

{
    "description": "Kromby 90",
    "typeID": 207,
    "nomineeID": 2640,
    "createdBy": 2630
}